name: spaces
description: Defining global spacing constants for building consistent and responsive apps.
version: 0.6.0
homepage: https://github.com/aloisdeniel/spaces

environment:
  sdk: '>=3.5.0 <4.0.0'

  flutter: '>=3.10.0'

dependencies:
  gap: ^3.0.1
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  flutter_lints: ^6.0.0

dev_dependencies:
  freezed: ^3.2.3
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter

flutter:
